---
- name: Install Apache and upload my web page
  hosts: all
  become: yes

  vars:
    source_folder: ./mywebsite2
    destin_folder: /var/www/html

  tasks:

  - name: Check and Print LINUX Versiom
    debug: var=ansible_os_family

  - block:

    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest

    - name: Start web servers and make it enable on boot for RedHat
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block:

    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest

    - name: Start web servers and make it enable on boot for Debian
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  - name: Generate INDEX.HTML file
    template: src={{ source_folder }}/index.j2 dest={{ destin_folder }}/index.html mode=555
    notify:
      - Restart Apache RedHat
      - Restart Apache Debian


  - name: Copy full file to servers
    copy: src={{ item }} dest={{ destin_folder }} mode=555
    with_fileglob: "{{ source_folder }}/*"

#  - name: Copy loop
#    copy: src={{ source_folder }}/{{ item }} dest={{ destin_folder }} mode=555
#    loop:
#      - "file4"
#      - "pro.art"
    notify:
      - Restart Apache RedHat
      - Restart Apache Debian



  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"
